name: Hacker News UI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install playwright browsers
        run: |
          playwright install chromium firefox 
          playwright install-deps chromium firefox

      - name: Create Report Directory
        run: |
          mkdir -p reports

      - name: Run test with chromium
        run: pytest --browser_name=chromium

      - name: Run test with firefox
        run: pytest --browser_name=firefox

      - name: Upload HTML test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: reports/
          retention-days: 15

